# Generated by Django 3.2.5 on 2021-07-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='authority',
            field=models.IntegerField(default=2),
        ),
    ]
