# Generated by Django 3.2.5 on 2021-07-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snscontrol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image9',
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
