# Generated by Django 3.2.5 on 2021-07-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snscontrol', '0002_auto_20210720_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_at',
        ),
    ]
