# Generated by Django 3.2.5 on 2021-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snscontrol', '0004_auto_20210720_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
    ]
