# Generated by Django 3.2.5 on 2021-08-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snscontrol', '0007_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='public_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
